//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEventos
    {
        public int evenCodigo { get; set; }
        public string evenNombre { get; set; }
        public string evenUbicacion { get; set; }
        public string evenParticipantes { get; set; }
        public string evenTodoDia { get; set; }
        public string evenFecha { get; set; }
        public Nullable<int> recoCodigo { get; set; }
        public string evenDescripcion { get; set; }
    
        public virtual tbRelacionadoCon tbRelacionadoCon { get; set; }
    }
}
