//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPosiblesClientes
    {
        public long clieIdentificacion { get; set; }
        public string clieEmpresa { get; set; }
        public string cliePrimerNombre { get; set; }
        public string clieSegundoNombre { get; set; }
        public string cliePrimerApellido { get; set; }
        public string clieSegundoApellido { get; set; }
        public string clieDireccion { get; set; }
        public string clieTelefono { get; set; }
        public string clieCorreo { get; set; }
    }
}
