//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTareas
    {
        public int tareCodigo { get; set; }
        public string tareTitular { get; set; }
        public string tareAsunto { get; set; }
        public string tareFechaVencimiento { get; set; }
        public string tareContacto { get; set; }
        public string tareCuenta { get; set; }
        public Nullable<int> estaCodigo { get; set; }
        public Nullable<int> prioCodigo { get; set; }
        public string tareEnviarMensaje { get; set; }
        public string tareRepetir { get; set; }
        public string tareDescripcion { get; set; }
    
        public virtual tbEstadoTareas tbEstadoTareas { get; set; }
        public virtual tbPrioridad tbPrioridad { get; set; }
    }
}
