//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.MVC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class incidencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public incidencia()
        {
            this.incidencia_comentarios = new HashSet<incidencia_comentarios>();
        }
    
        public int id { get; set; }
        public Nullable<long> identificacion { get; set; }
        public string primer_nombre { get; set; }
        public string segundo_nombre { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public Nullable<int> estado_incidencia_id { get; set; }
        public Nullable<int> tipo_incidencia_id { get; set; }
    
        public virtual estado_incidencia estado_incidencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<incidencia_comentarios> incidencia_comentarios { get; set; }
        public virtual tipo_incidencia tipo_incidencia { get; set; }
    }
}
