//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.MVC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class incidencia_comentarios
    {
        public int id { get; set; }
        public Nullable<int> incidencia_id { get; set; }
        public string comentarios { get; set; }
        public Nullable<int> estado_incidencia_id { get; set; }
    
        public virtual estado_incidencia estado_incidencia { get; set; }
        public virtual incidencia incidencia { get; set; }
    }
}
