//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.MVC.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdGeneralEntities : DbContext
    {
        public bdGeneralEntities()
            : base("name=bdGeneralEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<estado_incidencia> estado_incidencia { get; set; }
        public virtual DbSet<incidencia> incidencia { get; set; }
        public virtual DbSet<incidencia_comentarios> incidencia_comentarios { get; set; }
        public virtual DbSet<tipo_incidencia> tipo_incidencia { get; set; }
    }
}
